DROP TABLE IF EXISTS SUBSCRIPTION;
CREATE TABLE SUBSCRIPTION( ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(250) NOT NULL, MONTHLY_PRICE VARCHAR(250) NOT NULL, LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO SUBSCRIPTION (NAME, MONTHLY_PRICE,LAST_UPDATE) VALUES
  ('SUBSCRIPTION-TV', '72.2',CURRENT_TIMESTAMP),
  ('SUBSCRIPTION-TABLET', '100',CURRENT_TIMESTAMP);